secrets: private.yml

tasks:
  download-tv-shows:
    priority: 1
    transmission: yes
    configure_series:
      settings:
        set:
          path: "/Users/mark/TV Shows/{{series_name}}/Season {{series_season}}/"
      from:
        trakt_list:
          username: '{{ secrets.trakt.username }}'
          password: '{{ secrets.trakt.password }}'
          api_key: '{{ secrets.trakt.api_key }}'
          series: watched
    inputs:
      - rss: { url: 'http://showrss.info/feeds/all.rss', silent: yes }          # ShowRSS
      - rss: { url: 'http://ezrss.it/feed/', silent: yes }                      # EZRSS
      - rss: { url: 'http://torrentz.eu/feed_verified?q=tv', silent: yes }      # Torrentz (Verified only, TV)
      - rss: { url: 'http://rss.bt-chat.com/?group=3', silent: yes }            # BT-Chat (EZTV)


  build-movie-queue:
    priority: 2
    accept_all: yes
    queue_movies: yes
    imdb_list:
      user_id: '{{ secrets.imdb.user_id }}'
      list: watchlist


  download-movie-queue:
    priority: 3
    interval: 2 hours
    movie_queue: yes
    transmission:
      path: /Users/mark/Movies
    quality: dvdrip+ <1080p # No screeners, no cams.
    torrent_alive: 10 # Ignore torrents with less than 10 seeds.
    # Search for all movie-queue entires in torrentz.
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - torrentz: verified
