secrets: private.yml

tasks:
  download-tv-shows:
    priority: 2
    transmission: yes
    configure_series:
      settings:
        set:
          path: "/Users/mark/TV Shows/{{series_name}}/Season {{series_season}}/"
        upgrade: yes
        quality: webrip+ <=720p
        identified_by: ep
        main_file_only: yes
      from:
        inputs:
          - trakt_list:
              username: '{{ secrets.trakt.username }}'
              password: '{{ secrets.trakt.password }}'
              api_key: '{{ secrets.trakt.api_key }}'
              series: watched
          - trakt_list:
              username: '{{ secrets.trakt.username }}'
              password: '{{ secrets.trakt.password }}'
              api_key: '{{ secrets.trakt.api_key }}'
              series: watchlist
    discover:
      what:
        - emit_series: yes
      from:
        - piratebay: yes
    pushbullet:
      apikey: '{{ secrets.pushbullet.apikey }}'
      title: 'Downloading - {{ series_name }}'
      body: 'Season {{ series_season }}, Episode {{ series_episode }}'


  download-nightlies:
    priority: 1
    transmission: yes
    series:
      - The Daily Show:
          identified_by: date
          path: "/Users/mark/TV Shows/The Daily Show with Jon Stewart/"
          main_file_only: yes
      - The Colbert Report:
          identified_by: date
          path: "/Users/mark/TV Shows/The Colbert Report/"
          main_file_only: yes
    inputs:
      - rss: http://rss.thepiratebay.se/205
      - rss: http://showrss.info/feeds/all.rss
      - rss: http://ezrss.it/feed/
      - rss: http://torrentz.eu/feed?q=tv
      - rss: http://rss.bt-chat.com/?group=3
    pushbullet:
      apikey: '{{ secrets.pushbullet.apikey }}'
      title: 'Downloading - {{ series_name }}'
      body: '{{ series_date }}'


  kimbus:
    priority: 5
    transmission: yes
    configure_series:
      settings:
        set:
          path: "/Users/mark/TV Shows/{{series_name}}/Season {{series_season}}/"
        upgrade: yes
        quality: webrip+ <=720p
        identified_by: ep
      from:
        inputs:
          - trakt_list:
              username: '{{ secrets.kimbus_trakt.username }}'
              api_key: '{{ secrets.kimbus_trakt.api_key }}'
              series: watchlist
    discover:
      what:
        - emit_series: yes
      from:
        - piratebay: yes


  build-movie-queue:
    priority: 3
    accept_all: yes
    queue_movies: yes
    trakt_list:
      username: '{{ secrets.trakt.username }}'
      password: '{{ secrets.trakt.password }}'
      api_key: '{{ secrets.trakt.api_key }}'
      movies: watchlist
    pushbullet:
      apikey: '{{ secrets.pushbullet.apikey }}'
      title: 'Added to Queue - {{ movie_name }}'
      body: ''


  kimbus-build-movie-queue:
    priority: 6
    accept_all: yes
    queue_movies: yes
    trakt_list:
      username: '{{ secrets.kimbus_trakt.username }}'
      api_key: '{{ secrets.kimbus_trakt.api_key }}'
      movies: watchlist


  download-movie-queue:
    priority: 4
    interval: 2 hours
    movie_queue: yes
    transmission:
      path: /Users/mark/Movies
    quality: dvdrip+ <1080p
    torrent_alive: 500
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - piratebay: yes
    pushbullet:
      apikey: '{{ secrets.pushbullet.apikey }}'
      title: 'Downloading - {{ movie_name }}'
      body: ''
